name: food_delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  get: ^4.7.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  google_maps_flutter_web: ^0.5.10
  http: ^1.3.0
  location: ^8.0.0
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts\Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-Regular.ttf