// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5lqap3fL8VuW_malLw-SONAfmm34her8',
    appId: '1:20716126165:web:a02865487d323e6890475c',
    messagingSenderId: '20716126165',
    projectId: 'hackathone-final-ea637',
    authDomain: 'hackathone-final-ea637.firebaseapp.com',
    storageBucket: 'hackathone-final-ea637.firebasestorage.app',
    measurementId: 'G-C5K0J817EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuBAvpdgY6MiV1sx2sDfuVYWVAme_3Xs4',
    appId: '1:20716126165:android:51fa73cdf36bbd7690475c',
    messagingSenderId: '20716126165',
    projectId: 'hackathone-final-ea637',
    storageBucket: 'hackathone-final-ea637.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzSlvsnwUmcr6UAM45XoYPrN-nHpia6sE',
    appId: '1:20716126165:ios:f5e8bc2578df34a090475c',
    messagingSenderId: '20716126165',
    projectId: 'hackathone-final-ea637',
    storageBucket: 'hackathone-final-ea637.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzSlvsnwUmcr6UAM45XoYPrN-nHpia6sE',
    appId: '1:20716126165:ios:f5e8bc2578df34a090475c',
    messagingSenderId: '20716126165',
    projectId: 'hackathone-final-ea637',
    storageBucket: 'hackathone-final-ea637.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5lqap3fL8VuW_malLw-SONAfmm34her8',
    appId: '1:20716126165:web:31cba689abc3d4c390475c',
    messagingSenderId: '20716126165',
    projectId: 'hackathone-final-ea637',
    authDomain: 'hackathone-final-ea637.firebaseapp.com',
    storageBucket: 'hackathone-final-ea637.firebasestorage.app',
    measurementId: 'G-1WLCK6ZRWC',
  );

}